# Generated by Django 2.1.1 on 2018-10-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255)),
        ),
    ]
